// Generates src/environments/environment.ts from the repo-root .env file.
// A real API_URL env var (e.g. injected by Aspire or a Docker build) takes
// precedence over the .env value. Runs via the npm prestart/prebuild hooks.
const fs = require('node:fs');
const path = require('node:path');

try {
  process.loadEnvFile(path.resolve(__dirname, '..', '..', '.env'));
} catch {
  // no .env present (e.g. Docker build) — rely on process env / default
}

const apiUrl = (process.env.API_URL ?? '').replace(/\/+$/, '');

const outDir = path.resolve(__dirname, '..', 'src', 'environments');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(
  path.join(outDir, 'environment.ts'),
  `// AUTO-GENERATED by scripts/set-env.js — do not edit or commit.
export const environment = {
  apiUrl: '${apiUrl}',
};
`,
);
console.log(`[set-env] environment.ts written (apiUrl='${apiUrl}')`);
